import { Product } from '../models/product.model';

export const PRODUCTS_DATA: Product[] = [
  {
    id: 1,
    title: 'HAVIT HV-G92 Gamepad',
    price: 120,
    currentPrice: 120,
    originalPrice: 160,
    discount: 25,
    image: 'assets/image/items/item-1.png',
    images: [
      'assets/image/items/item-1.png',
      'assets/image/items/item-2.png',
      'assets/image/items/item-3.png',
      'assets/image/items/item-4.png',
    ],
    rating: 5,
    ratingCount: 88,
    description:
      'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal',
    colors: ['#000000', '#FF0000'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 1,
    title: 'HAVIT HV-G92 Gamepad',
    price: 120,
    currentPrice: 120,
    originalPrice: 160,
    discount: 25,
    image: 'assets/image/items/item-1.png',
    images: [
      'assets/image/items/item-1.png',
      'assets/image/items/item-2.png',
      'assets/image/items/item-3.png',
      'assets/image/items/item-4.png',
    ],
    rating: 5,
    ratingCount: 88,
    description:
      'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal',
    colors: ['#000000', '#FF0000'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 1,
    title: 'HAVIT HV-G92 Gamepad',
    price: 120,
    currentPrice: 120,
    originalPrice: 160,
    discount: 25,
    image: 'assets/image/items/item-1.png',
    images: [
      'assets/image/items/item-1.png',
      'assets/image/items/item-2.png',
      'assets/image/items/item-3.png',
      'assets/image/items/item-4.png',
    ],
    rating: 5,
    ratingCount: 88,
    description:
      'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal',
    colors: ['#000000', '#FF0000'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 1,
    title: 'HAVIT HV-G92 Gamepad',
    price: 120,
    currentPrice: 120,
    originalPrice: 160,
    discount: 25,
    image: 'assets/image/items/item-1.png',
    images: [
      'assets/image/items/item-1.png',
      'assets/image/items/item-2.png',
      'assets/image/items/item-3.png',
      'assets/image/items/item-4.png',
    ],
    rating: 5,
    ratingCount: 88,
    description:
      'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal',
    colors: ['#000000', '#FF0000'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 1,
    title: 'HAVIT HV-G92 Gamepad',
    price: 120,
    currentPrice: 120,
    originalPrice: 160,
    discount: 25,
    image: 'assets/image/items/item-1.png',
    images: [
      'assets/image/items/item-1.png',
      'assets/image/items/item-2.png',
      'assets/image/items/item-3.png',
      'assets/image/items/item-4.png',
    ],
    rating: 5,
    ratingCount: 88,
    description:
      'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal',
    colors: ['#000000', '#FF0000'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 1,
    title: 'HAVIT HV-G92 Gamepad',
    price: 120,
    currentPrice: 120,
    originalPrice: 160,
    discount: 25,
    image: 'assets/image/items/item-1.png',
    images: [
      'assets/image/items/item-1.png',
      'assets/image/items/item-2.png',
      'assets/image/items/item-3.png',
      'assets/image/items/item-4.png',
    ],
    rating: 5,
    ratingCount: 88,
    description:
      'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal',
    colors: ['#000000', '#FF0000'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
];
